### ISSUE TITLE
Configuring Google Cloud/Github Actions

### ISSUE THREAD

**Issue by Hatcher** [aablsk/sd-dreambooth#1]
Hey, I was trying to figure out the github actions configuration but am not clear on the steps I need to take. Any chance you have a guide on getting those steps setup?

**Comment by aablsk** [comment]
Dear @Hatcher,

**please note that as stated in the README.md this code is only to be used in demonstration sessions that I've held and I actively advise against deploying this into any environment (no warranties, may contain significant security flaws, too). Please consider this repo more an as inspiration than anything else.**

W.r.t. github actions: I'm not entirely sure what exactly you'd like to do as part of github actions. 

**Hypothesis A: You'd like to build the necessary docker images with Github Actions.** 
In this case I'd suggest taking a look at the cloudbuild.yaml files and translate them into GitHub Actions definitions (or just using Cloud Build instead of GithubActions).

**Hypothesis B: You'd like to do the actual fine-tuning of the model with GitHub Actions.** 
Stable Diffusion fine-tuning requires a GPU with at least 16GB memory. I'm not sure whether GitHub offers such an agent configuration. This repository uses a (kubeflow pipeline)[https://github.com/aablsk/sd-dreambooth/blob/main/fine_tune/pipeline/pipeline.py] for fine-tuning. Job instances for this pipeline can be created with (this script)[https://github.com/aablsk/sd-dreambooth/blob/main/fine_tune/pipeline/create_pipeline_job.py] which could be integrated into something like Github Actions. Triggers could be anything from additional files being added to a Google Cloud Storage bucket to a manually triggered event.

Warm regards,
aablsk

**Comment by Hatcher** [comment]
Hey, yeah totally here you about this being a POC, I had misread the readme and was trying to setup a github action to run the build pipeline. On further reading I found: https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github?generation=2nd-gen
